name: Build
on: [push]

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Create artifact
        shell: bash
        run: |
          echo ${GITHUB_SHA::6} > tag.txt
      - name: Upload artifact with image tag
        uses: actions/upload-artifact@v2
        with:
          name: image-tag
          path: tag.txt
